// =============================================
// MOCK DATA
// Replace API routes with real DB queries once
// you've set up Neon + run the schema.sql file.
// =============================================
import { AIModel, NewsItem, StatItem } from './types';

export const MOCK_MODELS: AIModel[] = [
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    company: 'OpenAI',
    logo: '🟢',
    release_date: '2024-05-13',
    model_type: 'multimodal',
    open_source: false,
    context_length: 128000,
    description: "OpenAI's flagship omni model. Reasons across text, audio, and images with GPT-4-level intelligence at 2× faster speed.",
    input_cost: 2.50,
    output_cost: 10.00,
    subscription_cost: 20,
    free_tier: true,
    capabilities: { coding: 95, reasoning: 96, multimodal: 98, vision: 97, speed: 88 },
    benchmarks: { MMLU: 88.7, HumanEval: 90.2, MATH: 76.6 },
    docs_url: 'https://platform.openai.com/docs',
    repo_url: null,
    trending_score: 98,
    tags: ['flagship', 'multimodal', 'vision'],
    isNew: false,
  },
  {
    id: 'claude-opus-4',
    name: 'Claude Opus 4',
    company: 'Anthropic',
    logo: '🟤',
    release_date: '2025-06-01',
    model_type: 'text',
    open_source: false,
    context_length: 200000,
    description: "Anthropic's most intelligent model, with exceptional reasoning, coding, and analysis. Optimized for complex, multi-step tasks.",
    input_cost: 15.00,
    output_cost: 75.00,
    subscription_cost: 20,
    free_tier: false,
    capabilities: { coding: 97, reasoning: 99, multimodal: 85, vision: 85, speed: 72 },
    benchmarks: { MMLU: 90.1, HumanEval: 93.7, MATH: 89.0 },
    docs_url: 'https://docs.anthropic.com',
    repo_url: null,
    trending_score: 96,
    tags: ['reasoning', 'coding', 'enterprise'],
    isNew: true,
  },
  {
    id: 'gemini-2-pro',
    name: 'Gemini 2.0 Pro',
    company: 'Google',
    logo: '🔵',
    release_date: '2025-02-05',
    model_type: 'multimodal',
    open_source: false,
    context_length: 2000000,
    description: "Google's next-gen multimodal AI with a 2M context window, native audio/video understanding, and agentic capabilities.",
    input_cost: 1.25,
    output_cost: 5.00,
    subscription_cost: 19.99,
    free_tier: true,
    capabilities: { coding: 90, reasoning: 92, multimodal: 99, vision: 97, speed: 91 },
    benchmarks: { MMLU: 90.0, HumanEval: 87.0, MATH: 86.5 },
    docs_url: 'https://ai.google.dev',
    repo_url: null,
    trending_score: 92,
    tags: ['multimodal', 'long-context', 'agentic'],
    isNew: true,
  },
  {
    id: 'llama-3-3-70b',
    name: 'Llama 3.3 70B',
    company: 'Meta',
    logo: '🦙',
    release_date: '2024-12-06',
    model_type: 'text',
    open_source: true,
    context_length: 128000,
    description: "Meta's open-source powerhouse. Matches GPT-4o performance at fraction of cost. 70B parameters, commercially usable.",
    input_cost: 0.23,
    output_cost: 0.92,
    subscription_cost: 0,
    free_tier: true,
    capabilities: { coding: 88, reasoning: 88, multimodal: 0, vision: 0, speed: 94 },
    benchmarks: { MMLU: 86.0, HumanEval: 88.4, MATH: 77.0 },
    docs_url: 'https://llama.meta.com',
    repo_url: 'https://github.com/meta-llama/llama3',
    trending_score: 89,
    tags: ['open-source', 'fast', 'cost-effective'],
    isNew: false,
  },
  {
    id: 'deepseek-r2',
    name: 'DeepSeek R2',
    company: 'DeepSeek',
    logo: '🔷',
    release_date: '2025-05-28',
    model_type: 'reasoning',
    open_source: true,
    context_length: 65536,
    description: "Chinese AI lab's latest reasoning model. Exceptional math and code at dramatically lower cost. Trained with novel MoE architecture.",
    input_cost: 0.14,
    output_cost: 2.19,
    subscription_cost: 0,
    free_tier: true,
    capabilities: { coding: 95, reasoning: 97, multimodal: 0, vision: 0, speed: 78 },
    benchmarks: { MMLU: 91.6, HumanEval: 95.0, MATH: 97.3 },
    docs_url: 'https://api-docs.deepseek.com',
    repo_url: 'https://github.com/deepseek-ai',
    trending_score: 94,
    tags: ['reasoning', 'open-source', 'math'],
    isNew: true,
  },
  {
    id: 'grok-3',
    name: 'Grok 3',
    company: 'xAI',
    logo: '✗',
    release_date: '2025-02-18',
    model_type: 'text',
    open_source: false,
    context_length: 131072,
    description: "xAI's Grok 3 with DeepSearch and Think modes. Trained on real-time X data. Excels at STEM and research tasks.",
    input_cost: 3.00,
    output_cost: 15.00,
    subscription_cost: 30,
    free_tier: false,
    capabilities: { coding: 89, reasoning: 92, multimodal: 60, vision: 72, speed: 85 },
    benchmarks: { MMLU: 87.5, HumanEval: 88.0, MATH: 93.3 },
    docs_url: 'https://docs.x.ai',
    repo_url: null,
    trending_score: 82,
    tags: ['real-time', 'research', 'STEM'],
    isNew: false,
  },
  {
    id: 'mistral-large-2',
    name: 'Mistral Large 2',
    company: 'Mistral AI',
    logo: '🌪️',
    release_date: '2024-07-24',
    model_type: 'text',
    open_source: false,
    context_length: 128000,
    description: 'Mistral\'s flagship model. Multilingual (80+ langs), strong coding, Apache 2.0 licensed for research use.',
    input_cost: 2.00,
    output_cost: 6.00,
    subscription_cost: 0,
    free_tier: true,
    capabilities: { coding: 90, reasoning: 87, multimodal: 0, vision: 0, speed: 90 },
    benchmarks: { MMLU: 84.0, HumanEval: 92.0, MATH: 76.0 },
    docs_url: 'https://docs.mistral.ai',
    repo_url: 'https://huggingface.co/mistralai',
    trending_score: 78,
    tags: ['multilingual', 'open-weights', 'efficient'],
    isNew: false,
  },
  {
    id: 'qwen-2-5-72b',
    name: 'Qwen 2.5 72B',
    company: 'Alibaba',
    logo: '🌸',
    release_date: '2024-09-19',
    model_type: 'text',
    open_source: true,
    context_length: 131072,
    description: "Alibaba's leading open-source model. Top-tier multilingual performance, strong math/coding, commercial license.",
    input_cost: 0.40,
    output_cost: 1.20,
    subscription_cost: 0,
    free_tier: true,
    capabilities: { coding: 87, reasoning: 86, multimodal: 0, vision: 0, speed: 92 },
    benchmarks: { MMLU: 85.0, HumanEval: 87.2, MATH: 83.1 },
    docs_url: 'https://qwen.readthedocs.io',
    repo_url: 'https://github.com/QwenLM/Qwen2.5',
    trending_score: 75,
    tags: ['open-source', 'multilingual', 'efficient'],
    isNew: false,
  },
];

export const MOCK_NEWS: NewsItem[] = [
  { id: 1, title: 'Anthropic releases Claude Opus 4 with breakthrough reasoning', source: 'TechCrunch', time: '2h ago', tag: 'Release', url: '#', hot: true },
  { id: 2, title: 'DeepSeek R2 achieves 97.3% on MATH benchmark, surpasses o3', source: 'Ars Technica', time: '4h ago', tag: 'Benchmark', url: '#', hot: true },
  { id: 3, title: 'Google expands Gemini 2.0 Pro to 2M token context window', source: 'The Verge', time: '6h ago', tag: 'Update', url: '#', hot: false },
  { id: 4, title: 'OpenAI reportedly training GPT-5 with 50T tokens', source: 'Bloomberg', time: '8h ago', tag: 'Rumor', url: '#', hot: true },
  { id: 5, title: 'Meta open-sources Llama 3.3 405B multilingual model', source: 'VentureBeat', time: '12h ago', tag: 'Open Source', url: '#', hot: false },
  { id: 6, title: 'Mistral AI raises $1B at $6B valuation for European AI expansion', source: 'Reuters', time: '1d ago', tag: 'Funding', url: '#', hot: false },
  { id: 7, title: "xAI's Grok 3 now available in API with 131K context", source: 'Wired', time: '1d ago', tag: 'API', url: '#', hot: false },
  { id: 8, title: 'AI agent frameworks become mainstream as coding AIs proliferate', source: 'MIT Tech Review', time: '2d ago', tag: 'Trend', url: '#', hot: false },
];

export const MOCK_STATS: StatItem[] = [
  { label: 'Models Tracked', value: '847', delta: '+12 this week' },
  { label: 'Companies Monitored', value: '143', delta: '+3 this week' },
  { label: 'API Endpoints', value: '2,341', delta: '+89 today' },
  { label: 'News Articles', value: '18,924', delta: '+127 today' },
];
